---
title: "GREGoR PCA results"
output: html_notebook
---

```{r}
library(AnVILGCP)
library(tidyverse)
library(jsonlite)
```

```{r}
peddy_bucket <- "gs://fc-secure-1264f593-842f-4934-80c6-5e9b5cc0ca80/peddy"
avlist(peddy_bucket, recursive=TRUE)
```

```{r}
avcopy(file.path(peddy_bucket, "V2/gregor_consortium_u06_V2.het_check.csv"), ".")
avcopy(file.path(peddy_bucket, "V2/gregor_consortium_u06_V2.background_pca.json"), ".")
```

```{r}
pcs <- read_csv("gregor_consortium_u06_V2.het_check.csv") %>%
  select(sample_id, starts_with("PC"))
```

```{r, fig.width=6, fig.height=6}
ggplot(pcs, aes(PC1, PC2)) + geom_point(alpha=0.5)
```


```{r}
pcs_ref <- fromJSON("gregor_consortium_u06_V2.background_pca.json") %>%
  mutate(group = paste("1000G", ancestry))
pcs_all <- bind_rows(pcs_ref, mutate(pcs, group="GREGoR"))
```


```{r, fig.width=6, fig.height=5}
colormap <- setNames(c("#1b9e77", "#d95f02", "#7570b3", "#e7298a", "#e6ab02", "#666666"),
                     c(paste("1000G", c("AFR", "AMR", "EAS", "EUR", "SAS")), "GREGoR"))
ggplot(pcs_all, aes(PC1, PC2, color=group)) + geom_point(alpha=0.5) + 
  scale_color_manual(values=colormap, breaks=names(colormap))
```

