---
title: "Population descriptors in GREGoR"
output: html_notebook
---

```{r}
library(AnVIL)
library(tidyverse)
library(RColorBrewer)
```

```{r}
workspace <- "GREGOR_COMBINED_CONSORTIUM_U12"
namespace <- "gregor-dcc"
participant <- avtable("participant", name=workspace, namespace=namespace)
```


```{r}
dat <- participant %>%
  select(participant_id, reported_race, reported_ethnicity) %>%
  mutate(reported_race = ifelse(grepl("|", reported_race, fixed=TRUE), "Multiple", reported_race)) %>%
  mutate(race_ethn = ifelse(reported_ethnicity %in% "Hispanic or Latino", 
                       ifelse(reported_race %in% "White", paste(reported_ethnicity, reported_race, sep="|"), 
                         ifelse(!is.na(reported_race), paste(reported_ethnicity, "Other", sep="|"), reported_ethnicity)), reported_race)) %>%
  mutate(race_ethn = ifelse(is.na(race_ethn), "Unknown", race_ethn))
dat %>%
 ggplot(aes(y = race_ethn)) + geom_bar()
```

```{r}
dat <- participant %>%
  select(participant_id, reported_race, reported_ethnicity) %>%
  mutate(reported_race = ifelse(grepl("|", reported_race, fixed=TRUE), "Multiple", reported_race)) %>%
  mutate(reported_race = ifelse(is.na(reported_race), "Unknown", reported_race)) %>%
  mutate(reported_ethnicity = ifelse(is.na(reported_ethnicity), "Unknown", reported_ethnicity))
table(dat$reported_race, dat$reported_ethnicity)
```

```{r}
#hm <- dat %>%
#  count(reported_race, reported_ethnicity)
# need to use table() to get zero counts
tmp <- table(dat$reported_race, dat$reported_ethnicity)
hm <- tibble(
  reported_race = rep(rownames(tmp), ncol(tmp)),
  reported_ethnicity = rep(colnames(tmp), each=nrow(tmp)),
  expand.grid(tmp)
) %>%
  rename(n = Var1) %>%
  mutate(n_censored = ifelse(n < 20 & n > 0, "<20", n))

races <- c(
  "American Indian or Alaska Native",
  "Asian",
  "Black or African American",
  "Middle Eastern or North African",
  "Native Hawaiian or Other Pacific Islander",
  "White",
  "Multiple",
  "Unknown"
)
hm$reported_race <- factor(hm$reported_race, levels=rev(races))

breaks <- c(-Inf, 0, 20, 50, 100, 500, 1000, 2000, 4000)
hm$n.cut <- cut(hm$n, breaks=breaks)
levels(hm$n.cut) <- paste0(breaks[-length(breaks)]+1, "-", prettyNum(breaks[-1]))
levels(hm$n.cut)[1] <- "0"
nlevs <-length(levels(hm$n.cut))
colors <- setNames(c("white", brewer.pal(nlevs, "Oranges")[1:nlevs-1]), levels(hm$n.cut))

ggplot(hm, aes(reported_ethnicity, reported_race, fill=n.cut)) +
  geom_tile() + 
  scale_fill_manual(values=colors, name="n") +
  geom_text(aes(label = n_censored)) + 
  theme_minimal() + 
  theme(panel.grid.minor=element_blank(),
        panel.grid.major=element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1)) +
  labs(x="", y="")
```
