---
title: "GREGoR Data Completeness"
output: html_notebook
---

Check data completeness in combined workspace

Updates: sort by required/not required, and then by completeness

```{r}
library(AnVIL)
library(AnvilDataModels)
library(dplyr)
library(tidyr)

options("GCLOUD_SDK_PATH"="~/Applications/google-cloud-sdk") # don't run in AnVIL workspace
workspace <- "GREGOR_COMBINED_CONSORTIUM_U1"
namespace <- "gregor-dcc"

model_url <- "https://raw.githubusercontent.com/UW-GAC/gregor_data_models/main/GREGoR_data_model.json"
model <- json_to_dm(model_url)
```

```{r}
participant <- avtable("participant", namespace=namespace, name=workspace)
id_map <- participant %>%
    select(participant_id, gregor_center)

phenotype <- avtable("phenotype", namespace=namespace, name=workspace) %>%
    left_join(id_map)

analyte <- avtable("analyte", namespace=namespace, name=workspace) %>%
    left_join(id_map)
id_map <- analyte %>%
    select(analyte_id, gregor_center)

experiment_dna_short_read <- avtable("experiment_dna_short_read", namespace=namespace, name=workspace) %>%
    left_join(id_map)
id_map <- experiment_dna_short_read %>%
    select(experiment_dna_short_read_id, gregor_center)

aligned_dna_short_read <- avtable("aligned_dna_short_read", namespace=namespace, name=workspace) %>%
    left_join(id_map)
```

# Fraction of non-missing values in each column

```{r}
completeness <- function(table_name) {
    t <- get(table_name)
    t[t == "NA"] <- NA
    t %>%
        group_by(gregor_center) %>%
        summarise_all(function(x) round(100*sum(!is.na(x))/n())) %>%
        pivot_longer(-gregor_center, names_to="field", values_to="completeness") %>%
        mutate(required=(field %in% attr(model[[table_name]], "required"))) %>%
        pivot_wider(names_from=gregor_center, values_from=completeness) %>%
        arrange(desc(required))
}
```

```{r}
completeness("participant")
```

```{r}
completeness("phenotype")
```

```{r}
completeness("analyte")
```

```{r}
completeness("experiment_dna_short_read")
```

```{r}
completeness("experiment_dna_short_read")
```

# HPO terms

## Probands

```{r}
phenotype[phenotype == "NA"] <- NA
participant %>%
    filter(proband_relationship %in% "Self") %>%
    left_join(phenotype) %>%
    group_by(gregor_center) %>%
    summarise(HPO_frac=round(100*sum(!is.na(term_id) & presence %in% "Present")/n()))
```

## Affected participants

```{r}
phenotype[phenotype == "NA"] <- NA
participant %>%
    filter(affected_status %in% "Affected") %>%
    left_join(phenotype) %>%
    group_by(gregor_center) %>%
    summarise(HPO_frac=round(100*sum(!is.na(term_id) & presence %in% "Present")/n()))
```
