---
title: Check files in workspaces
author: DCC
date: "`r Sys.Date()`"
editor_options: 
  chunk_output_type: console
output:
  html_document:
    toc: true
    toc_depth: 2
---

```{r install_packages, eval=FALSE}
install.packages(c(
  #"tidyverse",
  "kableExtra"
))
```

```{r libraries}
library(tools)
library(AnVIL)
library(tidyverse)
library(knitr)
```


```{r constants}
UPLOAD_CYCLE <- "U10"
ALL_CYCLES <- c(paste0("U0", 2:9), paste0("U", 10))

centers <- list(
  GRU=c("BCM", "CNH_I", "UCI", "GSS", "BROAD", "UW_CRDR"),
  HMB=c("BROAD", "UW_CRDR")
)
WORKSPACES_TO_KEEP <- lapply(ALL_CYCLES, function(cycle) {
  lapply(names(centers), function(consent) 
  paste("anvil-datastorage/AnVIL_GREGoR", centers[[consent]], cycle, consent, sep="_")
)}) %>% unlist() %>% sort()
```

# Look up bucket for each workspace.

```{r}
WORKSPACES <- avworkspaces() %>%
  mutate(workspace=file.path(namespace, name)) %>%
  filter(workspace %in% WORKSPACES_TO_KEEP) %>%
  # Extract upload_cycle
  mutate(
    upload_cycle = str_extract(workspace, "_(U\\d+)", group=1)
  ) %>%
  # Add bucket path using avbucket
  rowwise() %>%
  mutate(
    path = avbucket(namespace=namespace, name=name)
  ) %>%
  select(workspace, namespace, name, upload_cycle, path)
WORKSPACES %>% select(workspace, upload_cycle, path) %>% kable()
```

# Pull out data tables from current workspaces

```{r get_data_tables}
CURRENT_WORKSPACES <- WORKSPACES %>%
  filter(upload_cycle == UPLOAD_CYCLE)
table_list <- list()
for (i in seq_along(CURRENT_WORKSPACES$workspace)) {
  workspace <- CURRENT_WORKSPACES$workspace[i]
  namespace <- CURRENT_WORKSPACES$namespace[i]
  name <- CURRENT_WORKSPACES$name[i]
  # Create a list for storing the tables.
  table_list[[workspace]] <- list()
  tables <- avtables(namespace=namespace, name=name)
  tmp_list <- list()
  for (table in tables$table) {
    tmp <- avtable(table, namespace=namespace, name=name) %>%
      # Only keep character type columns.
      select(where(is.character)) %>%
      # Add row numbers to have a key for the column.
      mutate(rownum=row_number()) %>%
      # Convert to long format.
      pivot_longer(!rownum, names_to="column", values_to="file") %>%
      # Only keep records where the value is gs.
      filter(str_detect(file, "^gs://")) %>%
      # no need to keep multiple rows with the same file
      select(-rownum) %>%
      distinct()
    tmp_list[[table]] <- tmp
    tmp <- bind_rows(tmp_list, .id="table")
    table_list[[i]] <- tmp
  }
}
table_data <- bind_rows(table_list, .id="referencing_workspace")
table_data %>% group_by(referencing_workspace) %>% count() %>% kable()
```

# Check files in all buckets

```{r get_files}
file_list <- list()
for (i in seq_along(WORKSPACES$workspace)) {
  bucket <- WORKSPACES$path[i]
  workspace <- WORKSPACES$workspace[i]
  
  top_level <- gsutil_ls(bucket, recursive=FALSE)
  subdirs <- top_level[str_detect(top_level, "/$")]
  # Don't check the notebooks and submissions directories.
  subdirs <- subdirs[!str_detect(subdirs, "notebooks|submissions")]
  # Using the ** makes the gsutil_ls command a lot faster.
  sub_levels <- lapply(subdirs, function(f) gsutil_ls(paste0(f, "**"), recursive=TRUE))
  tmp <- tibble(file=c(top_level, unlist(sub_levels)))
  
  file_list[[workspace]] <- tmp
}

file_data <- bind_rows(file_list, .id="workspace")
file_data %>% group_by(workspace) %>% count() %>% kable()
```

## Check if each file is referenced in a data table in a current workspace

```{r}
tmp <- file_data %>%
  # Which tables are the files referenced in?
  left_join(table_data, by = "file") %>%
  select(workspace, file, referencing_workspace) %>%
  arrange(workspace, file, referencing_workspace)
```

```{r}
x <- tmp %>% 
  group_by(workspace, file) %>%
  summarise(
    n_workspaces=length(unique(na.omit(referencing_workspace)))
  ) %>%
  ungroup() %>%
  mutate(filetype = file_ext(file)) %>%
  filter(filetype != "") %>% # remove directories
  mutate(center=str_match(workspace, "anvil-datastorage/AnVIL_GREGoR_([A-Z_]+?)_U")[,2])

x0 <- x %>%
  filter(n_workspaces == 0) %>%
  select(-n_workspaces) %>%
  mutate(center = ifelse(center == "CNH_I", "UCI", center))

x1 <- x0 %>%
    filter(filetype %in% c("bam", "bai", "cram", "crai"))
```

## Summary of files not referenced in current workspaces by file type

```{r}
x0 %>%
  group_by(filetype, workspace) %>%
  count() %>%
  kable()
```

## Summary of bam/cram files not referenced in current workspaces by center

```{r}
x1 %>%
  group_by(center, workspace, filetype) %>%
  count() %>%
  kable()
```


## Save a list of bam/cram/index files per RC

```{r}
combined_bucket <- avbucket(namespace="gregor-dcc", name=paste0("GREGOR_COMBINED_CONSORTIUM_", UPLOAD_CYCLE))
uri <- paste0(combined_bucket, "/", UPLOAD_CYCLE, "_QC")
for (category in unique(x0$center)) {
  outfile <- paste(category, UPLOAD_CYCLE, "files_not_referenced_in_data_tables.tsv", sep="_")
  x1_out <- x1 %>%
    filter(center == !! category) %>%
    arrange(workspace, file, filetype)
  if (nrow(x1_out) > 0) {
    write_tsv(x1_out, outfile)
    gsutil_cp(outfile, file.path(uri, outfile))
    # copy to workspaces so RCs can access
    rc_uri <- avbucket(namespace="anvil-datastorage", 
                       name=paste("AnVIL_GREGoR", category, UPLOAD_CYCLE, "GRU", sep="_"))
    gsutil_cp(outfile, file.path(uri, outfile))
    gsutil_cp(outfile, file.path(rc_uri, "post_upload_qc", outfile))
  }
}
```



